export const COLAB_MAP = {
    "BEATRIZ": "PREENCHER_UID",
    "VANESSA OLIVEIRA": "PREENCHER_UID",
    "VANESSA FALBI": "PREENCHER_UID",
    "MISLAINE": "0AcMVLQVb5bxyaAWqB1dnCGV5D23",
    "JOAB": "PREENCHER_UID",
    "KATIA": "PREENCHER_UID",
    "PAMELA POSSETI": "PREENCHER_UID",
    "HELENA": "PREENCHER_UID"
};
